spring:
    application:
        name: hoseoHoui
    profiles:
        active: local
        include: oauth
    web:
        resources:
            add-mappings: false
server:
    port: 8080
    servlet:
        context-path: /api/v1

